// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpE5CYeSHysQsyiu2d2iX1MxR7CEI0Ujw',
    appId: '1:237528939048:web:4a81c8c9ef01fd510ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    authDomain: 'e-ecommerce-f3bee.firebaseapp.com',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    measurementId: 'G-C29HPEHR5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4YAlJdb6Wj0V2kAJKnXgk0_pBVYQ20uI',
    appId: '1:237528939048:android:1a22d458c64aaa1e0ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_E5niJk-i7ZT1ss_90c-IF3WUT5jFko',
    appId: '1:237528939048:ios:86886979a1b575360ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_E5niJk-i7ZT1ss_90c-IF3WUT5jFko',
    appId: '1:237528939048:ios:86886979a1b575360ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpE5CYeSHysQsyiu2d2iX1MxR7CEI0Ujw',
    appId: '1:237528939048:web:f2b062e8e994847f0ed31d',
    messagingSenderId: '237528939048',
    projectId: 'e-ecommerce-f3bee',
    authDomain: 'e-ecommerce-f3bee.firebaseapp.com',
    storageBucket: 'e-ecommerce-f3bee.appspot.com',
    measurementId: 'G-FL4NPLBEJX',
  );
}
